import os
import random
from datetime import timedelta

from django.utils import timezone
from django.db import transaction
from django.contrib.auth import get_user_model

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "issue_tracker.settings")

import django  # noqa: E402
django.setup()  # noqa: E402

from labels.models import Label  # noqa: E402
from issues.models import Issue, IssueLabel, IssueHistory  # noqa: E402
from comments.models import Comment  # noqa: E402


User = get_user_model()

LABELS = [
    ("bug", "#d73a4a"),
    ("feature", "#0e8a16"),
    ("urgent", "#b60205"),
    ("backend", "#5319e7"),
    ("frontend", "#1d76db"),
]

@transaction.atomic
def run():
    # Users
    admin, _ = User.objects.get_or_create(
        username="admin",
        defaults={"email": "admin@example.com", "is_staff": True, "is_superuser": True},
    )
    if not admin.has_usable_password():
        admin.set_password("admin123")
        admin.save()

    users = [admin]
    for u in ["john", "jane", "rahul", "neha", "arjun"]:
        obj, _ = User.objects.get_or_create(username=u, defaults={"email": f"{u}@example.com"})
        if not obj.has_usable_password():
            obj.set_password("test123")
            obj.save()
        users.append(obj)

    # Labels
    label_objs = []
    for name, color in LABELS:
        l, _ = Label.objects.get_or_create(name=name, defaults={"color": color})
        label_objs.append(l)

    # Issues
    issues = []
    for i in range(1, 21):
        creator = random.choice(users)
        assignee = random.choice(users)
        status = random.choice(["open", "in_progress", "resolved", "closed"])
        priority = random.choice(["low", "medium", "high", "critical"])

        issue = Issue.objects.create(
            title=f"Issue #{i}: Sample {status} {priority}",
            description="Generated by seed script.",
            creator=creator,
            assignee=assignee if assignee != creator else None,
            status=status,
            priority=priority,
            version=0,
            resolved_at=timezone.now() - timedelta(days=random.randint(0, 10)) if status in ["resolved", "closed"] else None,
        )
        issues.append(issue)

        # Attach 1-3 labels
        for l in random.sample(label_objs, k=random.randint(1, 3)):
            IssueLabel.objects.get_or_create(issue=issue, label=l)

        # Comments (0-4)
        for c in range(random.randint(0, 4)):
            Comment.objects.create(
                issue=issue,
                author=random.choice(users),
                body=f"Comment {c+1} on issue #{issue.id}",
            )

        # History (simple examples)
        IssueHistory.objects.create(
            issue=issue,
            changed_by=creator,
            field_name="status",
            old_value="",
            new_value=status,
        )
        IssueHistory.objects.create(
            issue=issue,
            changed_by=creator,
            field_name="priority",
            old_value="",
            new_value=priority,
        )

    print(f"Seeded: users={User.objects.count()}, labels={Label.objects.count()}, issues={Issue.objects.count()}, comments={Comment.objects.count()}, history={IssueHistory.objects.count()}")

if __name__ == "__main__":
    run()
